package org.tempuri;

import java.net.URL;
import jakarta.annotation.Generated;
import javax.xml.namespace.QName;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import com.rusguard.client.ILMonitoringService;
import com.rusguard.client.ILNetworkConfigurationService;
import com.rusguard.client.ILNetworkService;
import com.rusguard.client.ILSubnetworkSubscribeService;
import jakarta.xml.ws.Service;

/**
 * This class was generated by Apache CXF 4.1.4
 * 2026-01-18T16:49:04.587+03:00
 * Generated source version: 4.1.4
 *
 */
@WebServiceClient(name = "LNetworkService",
                  wsdlLocation = "classpath:wsdl/LNetworkServer.wsdl",
                  targetNamespace = "http://tempuri.org/")
@Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-01-18T16:49:04.587+03:00", comments = "Apache CXF 4.1.4")
public class LNetworkService extends Service {

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-01-18T16:49:04.587+03:00")
    public static final URL WSDL_LOCATION;

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-01-18T16:49:04.587+03:00")
    public static final QName SERVICE = new QName("http://tempuri.org/", "LNetworkService");
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-01-18T16:49:04.587+03:00")
    public static final QName BasicHttpBindingILSubnetworkSubscribeService = new QName("http://tempuri.org/", "BasicHttpBinding_ILSubnetworkSubscribeService");
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-01-18T16:49:04.587+03:00")
    public static final QName BasicHttpBindingILNetworkService = new QName("http://tempuri.org/", "BasicHttpBinding_ILNetworkService");
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-01-18T16:49:04.587+03:00")
    public static final QName BasicHttpBindingILNetworkConfigurationService = new QName("http://tempuri.org/", "BasicHttpBinding_ILNetworkConfigurationService");
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-01-18T16:49:04.587+03:00")
    public static final QName BasicHttpBindingIOperatorContract = new QName("http://tempuri.org/", "BasicHttpBinding_IOperatorContract");
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-01-18T16:49:04.587+03:00")
    public static final QName BasicHttpBindingILMonitoringService = new QName("http://tempuri.org/", "BasicHttpBinding_ILMonitoringService");
    static {
        URL url = LNetworkService.class.getClassLoader().getResource("wsdl/LNetworkServer.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(LNetworkService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "classpath:wsdl/LNetworkServer.wsdl");
        }
        WSDL_LOCATION = url;
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-01-18T16:49:04.587+03:00")
    public LNetworkService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-01-18T16:49:04.587+03:00")
    public LNetworkService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-01-18T16:49:04.587+03:00")
    public LNetworkService() {
        super(WSDL_LOCATION, SERVICE);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-01-18T16:49:04.587+03:00")
    public LNetworkService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-01-18T16:49:04.587+03:00")
    public LNetworkService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-01-18T16:49:04.587+03:00")
    public LNetworkService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ILSubnetworkSubscribeService
     */
    @WebEndpoint(name = "BasicHttpBinding_ILSubnetworkSubscribeService")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-01-18T16:49:04.587+03:00")
    public ILSubnetworkSubscribeService getBasicHttpBindingILSubnetworkSubscribeService() {
        return super.getPort(BasicHttpBindingILSubnetworkSubscribeService, ILSubnetworkSubscribeService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ILSubnetworkSubscribeService
     */
    @WebEndpoint(name = "BasicHttpBinding_ILSubnetworkSubscribeService")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-01-18T16:49:04.587+03:00")
    public ILSubnetworkSubscribeService getBasicHttpBindingILSubnetworkSubscribeService(WebServiceFeature... features) {
        return super.getPort(BasicHttpBindingILSubnetworkSubscribeService, ILSubnetworkSubscribeService.class, features);
    }


    /**
     *
     * @return
     *     returns ILNetworkService
     */
    @WebEndpoint(name = "BasicHttpBinding_ILNetworkService")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-01-18T16:49:04.587+03:00")
    public ILNetworkService getBasicHttpBindingILNetworkService() {
        return super.getPort(BasicHttpBindingILNetworkService, ILNetworkService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ILNetworkService
     */
    @WebEndpoint(name = "BasicHttpBinding_ILNetworkService")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-01-18T16:49:04.587+03:00")
    public ILNetworkService getBasicHttpBindingILNetworkService(WebServiceFeature... features) {
        return super.getPort(BasicHttpBindingILNetworkService, ILNetworkService.class, features);
    }


    /**
     *
     * @return
     *     returns ILNetworkConfigurationService
     */
    @WebEndpoint(name = "BasicHttpBinding_ILNetworkConfigurationService")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-01-18T16:49:04.587+03:00")
    public ILNetworkConfigurationService getBasicHttpBindingILNetworkConfigurationService() {
        return super.getPort(BasicHttpBindingILNetworkConfigurationService, ILNetworkConfigurationService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ILNetworkConfigurationService
     */
    @WebEndpoint(name = "BasicHttpBinding_ILNetworkConfigurationService")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-01-18T16:49:04.587+03:00")
    public ILNetworkConfigurationService getBasicHttpBindingILNetworkConfigurationService(WebServiceFeature... features) {
        return super.getPort(BasicHttpBindingILNetworkConfigurationService, ILNetworkConfigurationService.class, features);
    }


    /**
     *
     * @return
     *     returns IOperatorContract
     */
    @WebEndpoint(name = "BasicHttpBinding_IOperatorContract")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-01-18T16:49:04.587+03:00")
    public IOperatorContract getBasicHttpBindingIOperatorContract() {
        return super.getPort(BasicHttpBindingIOperatorContract, IOperatorContract.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IOperatorContract
     */
    @WebEndpoint(name = "BasicHttpBinding_IOperatorContract")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-01-18T16:49:04.587+03:00")
    public IOperatorContract getBasicHttpBindingIOperatorContract(WebServiceFeature... features) {
        return super.getPort(BasicHttpBindingIOperatorContract, IOperatorContract.class, features);
    }


    /**
     *
     * @return
     *     returns ILMonitoringService
     */
    @WebEndpoint(name = "BasicHttpBinding_ILMonitoringService")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-01-18T16:49:04.587+03:00")
    public ILMonitoringService getBasicHttpBindingILMonitoringService() {
        return super.getPort(BasicHttpBindingILMonitoringService, ILMonitoringService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ILMonitoringService
     */
    @WebEndpoint(name = "BasicHttpBinding_ILMonitoringService")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-01-18T16:49:04.587+03:00")
    public ILMonitoringService getBasicHttpBindingILMonitoringService(WebServiceFeature... features) {
        return super.getPort(BasicHttpBindingILMonitoringService, ILMonitoringService.class, features);
    }

}
