
package com.rusguard.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import jakarta.annotation.Generated;
import javax.xml.namespace.QName;
import org.tempuri.LNetworkService;
import jakarta.jws.WebMethod;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.1.4
 * 2026-01-18T16:49:03.078+03:00
 * Generated source version: 4.1.4
 *
 */
@Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-01-18T16:49:03.078+03:00", comments = "Apache CXF 4.1.4")
public final class ILMonitoringService_BasicHttpBindingILMonitoringService_Client {

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-01-18T16:49:03.078+03:00")
    private static final QName SERVICE_NAME = new QName("http://tempuri.org/", "LNetworkService");

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-01-18T16:49:03.078+03:00")
    private ILMonitoringService_BasicHttpBindingILMonitoringService_Client() {
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-01-18T16:49:03.078+03:00")
    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = LNetworkService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        LNetworkService ss = new LNetworkService(wsdlURL, SERVICE_NAME);
        ILMonitoringService port = ss.getBasicHttpBindingILMonitoringService();

        {
        System.out.println("Invoking ping...");
        port.ping();


        }

        System.exit(0);
    }

}
