
package com.rusguard.client;

import jakarta.annotation.Generated;
import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.4
 * 2026-01-18T16:49:04.525+03:00
 * Generated source version: 4.1.4
 */

@WebFault(name = "TimeoutException", targetNamespace = "http://schemas.datacontract.org/2004/07/System")
@Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-01-18T16:49:04.525+03:00", comments = "Apache CXF 4.1.4")
public class ILNetworkConfigurationServiceFindLanConverter2TimeoutExceptionFaultFaultMessage extends java.lang.Exception {

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-01-18T16:49:04.525+03:00")
    private org.datacontract.schemas._2004._07.system.TimeoutException faultInfo;

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-01-18T16:49:04.525+03:00")
    public ILNetworkConfigurationServiceFindLanConverter2TimeoutExceptionFaultFaultMessage() {
        super();
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-01-18T16:49:04.525+03:00")
    public ILNetworkConfigurationServiceFindLanConverter2TimeoutExceptionFaultFaultMessage(String message) {
        super(message);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-01-18T16:49:04.525+03:00")
    public ILNetworkConfigurationServiceFindLanConverter2TimeoutExceptionFaultFaultMessage(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-01-18T16:49:04.525+03:00")
    public ILNetworkConfigurationServiceFindLanConverter2TimeoutExceptionFaultFaultMessage(String message, org.datacontract.schemas._2004._07.system.TimeoutException timeoutException) {
        super(message);
        this.faultInfo = timeoutException;
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-01-18T16:49:04.525+03:00")
    public ILNetworkConfigurationServiceFindLanConverter2TimeoutExceptionFaultFaultMessage(String message, org.datacontract.schemas._2004._07.system.TimeoutException timeoutException, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = timeoutException;
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-01-18T16:49:04.525+03:00")
    public org.datacontract.schemas._2004._07.system.TimeoutException getFaultInfo() {
        return this.faultInfo;
    }
}
