
package com.rusguard.client;

import jakarta.annotation.Generated;
import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.4
 * 2026-01-18T16:49:03.805+03:00
 * Generated source version: 4.1.4
 */

@WebFault(name = "ArgumentException", targetNamespace = "http://schemas.datacontract.org/2004/07/System")
@Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-01-18T16:49:03.805+03:00", comments = "Apache CXF 4.1.4")
public class ILNetworkConfigurationServiceGetIncidentArchiveReportArgumentExceptionFaultFaultMessage extends java.lang.Exception {

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-01-18T16:49:03.805+03:00")
    private org.datacontract.schemas._2004._07.system.ArgumentException faultInfo;

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-01-18T16:49:03.805+03:00")
    public ILNetworkConfigurationServiceGetIncidentArchiveReportArgumentExceptionFaultFaultMessage() {
        super();
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-01-18T16:49:03.805+03:00")
    public ILNetworkConfigurationServiceGetIncidentArchiveReportArgumentExceptionFaultFaultMessage(String message) {
        super(message);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-01-18T16:49:03.805+03:00")
    public ILNetworkConfigurationServiceGetIncidentArchiveReportArgumentExceptionFaultFaultMessage(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-01-18T16:49:03.805+03:00")
    public ILNetworkConfigurationServiceGetIncidentArchiveReportArgumentExceptionFaultFaultMessage(String message, org.datacontract.schemas._2004._07.system.ArgumentException argumentException) {
        super(message);
        this.faultInfo = argumentException;
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-01-18T16:49:03.805+03:00")
    public ILNetworkConfigurationServiceGetIncidentArchiveReportArgumentExceptionFaultFaultMessage(String message, org.datacontract.schemas._2004._07.system.ArgumentException argumentException, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = argumentException;
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-01-18T16:49:03.805+03:00")
    public org.datacontract.schemas._2004._07.system.ArgumentException getFaultInfo() {
        return this.faultInfo;
    }
}
