
package com.rusguard.client;

import jakarta.annotation.Generated;
import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.4
 * 2026-01-18T16:49:04.447+03:00
 * Generated source version: 4.1.4
 */

@WebFault(name = "SocketException", targetNamespace = "http://schemas.datacontract.org/2004/07/System.Net.Sockets")
@Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-01-18T16:49:04.447+03:00", comments = "Apache CXF 4.1.4")
public class ILNetworkConfigurationServiceBroadcastFindLanConvertersSocketExceptionFaultFaultMessage extends java.lang.Exception {

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-01-18T16:49:04.447+03:00")
    private org.datacontract.schemas._2004._07.system_net.SocketException faultInfo;

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-01-18T16:49:04.447+03:00")
    public ILNetworkConfigurationServiceBroadcastFindLanConvertersSocketExceptionFaultFaultMessage() {
        super();
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-01-18T16:49:04.447+03:00")
    public ILNetworkConfigurationServiceBroadcastFindLanConvertersSocketExceptionFaultFaultMessage(String message) {
        super(message);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-01-18T16:49:04.447+03:00")
    public ILNetworkConfigurationServiceBroadcastFindLanConvertersSocketExceptionFaultFaultMessage(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-01-18T16:49:04.447+03:00")
    public ILNetworkConfigurationServiceBroadcastFindLanConvertersSocketExceptionFaultFaultMessage(String message, org.datacontract.schemas._2004._07.system_net.SocketException socketException) {
        super(message);
        this.faultInfo = socketException;
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-01-18T16:49:04.447+03:00")
    public ILNetworkConfigurationServiceBroadcastFindLanConvertersSocketExceptionFaultFaultMessage(String message, org.datacontract.schemas._2004._07.system_net.SocketException socketException, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = socketException;
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-01-18T16:49:04.447+03:00")
    public org.datacontract.schemas._2004._07.system_net.SocketException getFaultInfo() {
        return this.faultInfo;
    }
}
