
package com.rusguard.client;

import jakarta.annotation.Generated;
import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.4
 * 2026-01-18T16:49:03.531+03:00
 * Generated source version: 4.1.4
 */

@WebFault(name = "ArgumentOutOfRangeException", targetNamespace = "http://schemas.datacontract.org/2004/07/System")
@Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-01-18T16:49:03.531+03:00", comments = "Apache CXF 4.1.4")
public class ILNetworkConfigurationServiceUpdateEmployeeTimeTableArgumentOutOfRangeExceptionFaultFaultMessage extends java.lang.Exception {

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-01-18T16:49:03.531+03:00")
    private org.datacontract.schemas._2004._07.system.ArgumentOutOfRangeException faultInfo;

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-01-18T16:49:03.531+03:00")
    public ILNetworkConfigurationServiceUpdateEmployeeTimeTableArgumentOutOfRangeExceptionFaultFaultMessage() {
        super();
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-01-18T16:49:03.531+03:00")
    public ILNetworkConfigurationServiceUpdateEmployeeTimeTableArgumentOutOfRangeExceptionFaultFaultMessage(String message) {
        super(message);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-01-18T16:49:03.531+03:00")
    public ILNetworkConfigurationServiceUpdateEmployeeTimeTableArgumentOutOfRangeExceptionFaultFaultMessage(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-01-18T16:49:03.531+03:00")
    public ILNetworkConfigurationServiceUpdateEmployeeTimeTableArgumentOutOfRangeExceptionFaultFaultMessage(String message, org.datacontract.schemas._2004._07.system.ArgumentOutOfRangeException argumentOutOfRangeException) {
        super(message);
        this.faultInfo = argumentOutOfRangeException;
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-01-18T16:49:03.531+03:00")
    public ILNetworkConfigurationServiceUpdateEmployeeTimeTableArgumentOutOfRangeExceptionFaultFaultMessage(String message, org.datacontract.schemas._2004._07.system.ArgumentOutOfRangeException argumentOutOfRangeException, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = argumentOutOfRangeException;
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-01-18T16:49:03.531+03:00")
    public org.datacontract.schemas._2004._07.system.ArgumentOutOfRangeException getFaultInfo() {
        return this.faultInfo;
    }
}
