
package com.rusguard.client;

import jakarta.annotation.Generated;
import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.4
 * 2026-01-18T16:49:04.366+03:00
 * Generated source version: 4.1.4
 */

@WebFault(name = "DataAlreadyExistsException", targetNamespace = "http://schemas.datacontract.org/2004/07/VVIInvestment.RusGuard.DAL.Entities.Exceptions")
@Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-01-18T16:49:04.366+03:00", comments = "Apache CXF 4.1.4")
public class ILNetworkConfigurationServiceAddWorkZonesToEmployeeGroupDataAlreadyExistsExceptionFaultFaultMessage extends java.lang.Exception {

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-01-18T16:49:04.366+03:00")
    private org.datacontract.schemas._2004._07.vviinvestment_rusguard_dal_entities.DataAlreadyExistsException faultInfo;

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-01-18T16:49:04.366+03:00")
    public ILNetworkConfigurationServiceAddWorkZonesToEmployeeGroupDataAlreadyExistsExceptionFaultFaultMessage() {
        super();
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-01-18T16:49:04.366+03:00")
    public ILNetworkConfigurationServiceAddWorkZonesToEmployeeGroupDataAlreadyExistsExceptionFaultFaultMessage(String message) {
        super(message);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-01-18T16:49:04.366+03:00")
    public ILNetworkConfigurationServiceAddWorkZonesToEmployeeGroupDataAlreadyExistsExceptionFaultFaultMessage(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-01-18T16:49:04.366+03:00")
    public ILNetworkConfigurationServiceAddWorkZonesToEmployeeGroupDataAlreadyExistsExceptionFaultFaultMessage(String message, org.datacontract.schemas._2004._07.vviinvestment_rusguard_dal_entities.DataAlreadyExistsException dataAlreadyExistsException) {
        super(message);
        this.faultInfo = dataAlreadyExistsException;
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-01-18T16:49:04.366+03:00")
    public ILNetworkConfigurationServiceAddWorkZonesToEmployeeGroupDataAlreadyExistsExceptionFaultFaultMessage(String message, org.datacontract.schemas._2004._07.vviinvestment_rusguard_dal_entities.DataAlreadyExistsException dataAlreadyExistsException, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = dataAlreadyExistsException;
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-01-18T16:49:04.366+03:00")
    public org.datacontract.schemas._2004._07.vviinvestment_rusguard_dal_entities.DataAlreadyExistsException getFaultInfo() {
        return this.faultInfo;
    }
}
