
package com.rusguard.client;

import jakarta.annotation.Generated;
import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.4
 * 2026-01-18T16:49:03.803+03:00
 * Generated source version: 4.1.4
 */

@WebFault(name = "DataNotFoundException", targetNamespace = "http://schemas.datacontract.org/2004/07/VVIInvestment.RusGuard.DAL.Entities.Exceptions")
@Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-01-18T16:49:03.803+03:00", comments = "Apache CXF 4.1.4")
public class ILNetworkConfigurationServiceAddAccessLevelsToVehicleDataNotFoundExceptionFaultFaultMessage extends java.lang.Exception {

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-01-18T16:49:03.803+03:00")
    private org.datacontract.schemas._2004._07.vviinvestment_rusguard_dal_entities.DataNotFoundException faultInfo;

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-01-18T16:49:03.803+03:00")
    public ILNetworkConfigurationServiceAddAccessLevelsToVehicleDataNotFoundExceptionFaultFaultMessage() {
        super();
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-01-18T16:49:03.803+03:00")
    public ILNetworkConfigurationServiceAddAccessLevelsToVehicleDataNotFoundExceptionFaultFaultMessage(String message) {
        super(message);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-01-18T16:49:03.803+03:00")
    public ILNetworkConfigurationServiceAddAccessLevelsToVehicleDataNotFoundExceptionFaultFaultMessage(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-01-18T16:49:03.803+03:00")
    public ILNetworkConfigurationServiceAddAccessLevelsToVehicleDataNotFoundExceptionFaultFaultMessage(String message, org.datacontract.schemas._2004._07.vviinvestment_rusguard_dal_entities.DataNotFoundException dataNotFoundException) {
        super(message);
        this.faultInfo = dataNotFoundException;
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-01-18T16:49:03.803+03:00")
    public ILNetworkConfigurationServiceAddAccessLevelsToVehicleDataNotFoundExceptionFaultFaultMessage(String message, org.datacontract.schemas._2004._07.vviinvestment_rusguard_dal_entities.DataNotFoundException dataNotFoundException, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = dataNotFoundException;
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-01-18T16:49:03.803+03:00")
    public org.datacontract.schemas._2004._07.vviinvestment_rusguard_dal_entities.DataNotFoundException getFaultInfo() {
        return this.faultInfo;
    }
}
