
package com.rusguard.client;

import jakarta.annotation.Generated;
import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.4
 * 2026-01-18T16:49:03.669+03:00
 * Generated source version: 4.1.4
 */

@WebFault(name = "InvalidOperationException", targetNamespace = "http://schemas.datacontract.org/2004/07/System")
@Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-01-18T16:49:03.669+03:00", comments = "Apache CXF 4.1.4")
public class ILNetworkConfigurationServiceRemoveCellInvalidOperationExceptionFaultFaultMessage extends java.lang.Exception {

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-01-18T16:49:03.669+03:00")
    private org.datacontract.schemas._2004._07.system.InvalidOperationException faultInfo;

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-01-18T16:49:03.669+03:00")
    public ILNetworkConfigurationServiceRemoveCellInvalidOperationExceptionFaultFaultMessage() {
        super();
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-01-18T16:49:03.669+03:00")
    public ILNetworkConfigurationServiceRemoveCellInvalidOperationExceptionFaultFaultMessage(String message) {
        super(message);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-01-18T16:49:03.669+03:00")
    public ILNetworkConfigurationServiceRemoveCellInvalidOperationExceptionFaultFaultMessage(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-01-18T16:49:03.669+03:00")
    public ILNetworkConfigurationServiceRemoveCellInvalidOperationExceptionFaultFaultMessage(String message, org.datacontract.schemas._2004._07.system.InvalidOperationException invalidOperationException) {
        super(message);
        this.faultInfo = invalidOperationException;
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-01-18T16:49:03.669+03:00")
    public ILNetworkConfigurationServiceRemoveCellInvalidOperationExceptionFaultFaultMessage(String message, org.datacontract.schemas._2004._07.system.InvalidOperationException invalidOperationException, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = invalidOperationException;
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-01-18T16:49:03.669+03:00")
    public org.datacontract.schemas._2004._07.system.InvalidOperationException getFaultInfo() {
        return this.faultInfo;
    }
}
