
package com.rusguard.client;

import jakarta.annotation.Generated;
import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.4
 * 2026-01-18T16:49:04.200+03:00
 * Generated source version: 4.1.4
 */

@WebFault(name = "ApplicationException", targetNamespace = "http://schemas.datacontract.org/2004/07/System")
@Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-01-18T16:49:04.200+03:00", comments = "Apache CXF 4.1.4")
public class ILNetworkConfigurationServiceGetSecureOSCamerasApplicationExceptionFaultFaultMessage extends java.lang.Exception {

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-01-18T16:49:04.200+03:00")
    private org.datacontract.schemas._2004._07.system.ApplicationException faultInfo;

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-01-18T16:49:04.200+03:00")
    public ILNetworkConfigurationServiceGetSecureOSCamerasApplicationExceptionFaultFaultMessage() {
        super();
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-01-18T16:49:04.200+03:00")
    public ILNetworkConfigurationServiceGetSecureOSCamerasApplicationExceptionFaultFaultMessage(String message) {
        super(message);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-01-18T16:49:04.200+03:00")
    public ILNetworkConfigurationServiceGetSecureOSCamerasApplicationExceptionFaultFaultMessage(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-01-18T16:49:04.200+03:00")
    public ILNetworkConfigurationServiceGetSecureOSCamerasApplicationExceptionFaultFaultMessage(String message, org.datacontract.schemas._2004._07.system.ApplicationException applicationException) {
        super(message);
        this.faultInfo = applicationException;
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-01-18T16:49:04.200+03:00")
    public ILNetworkConfigurationServiceGetSecureOSCamerasApplicationExceptionFaultFaultMessage(String message, org.datacontract.schemas._2004._07.system.ApplicationException applicationException, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = applicationException;
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-01-18T16:49:04.200+03:00")
    public org.datacontract.schemas._2004._07.system.ApplicationException getFaultInfo() {
        return this.faultInfo;
    }
}
