
package com.rusguard.client;

import jakarta.annotation.Generated;
import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.4
 * 2026-01-18T16:49:03.360+03:00
 * Generated source version: 4.1.4
 */

@WebFault(name = "NotSupportedException", targetNamespace = "http://schemas.datacontract.org/2004/07/System")
@Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-01-18T16:49:03.360+03:00", comments = "Apache CXF 4.1.4")
public class ILNetworkServiceCheckEbsBiometricStatusNotSupportedExceptionFaultFaultMessage extends java.lang.Exception {

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-01-18T16:49:03.360+03:00")
    private org.datacontract.schemas._2004._07.system.NotSupportedException faultInfo;

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-01-18T16:49:03.360+03:00")
    public ILNetworkServiceCheckEbsBiometricStatusNotSupportedExceptionFaultFaultMessage() {
        super();
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-01-18T16:49:03.360+03:00")
    public ILNetworkServiceCheckEbsBiometricStatusNotSupportedExceptionFaultFaultMessage(String message) {
        super(message);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-01-18T16:49:03.360+03:00")
    public ILNetworkServiceCheckEbsBiometricStatusNotSupportedExceptionFaultFaultMessage(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-01-18T16:49:03.360+03:00")
    public ILNetworkServiceCheckEbsBiometricStatusNotSupportedExceptionFaultFaultMessage(String message, org.datacontract.schemas._2004._07.system.NotSupportedException notSupportedException) {
        super(message);
        this.faultInfo = notSupportedException;
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-01-18T16:49:03.360+03:00")
    public ILNetworkServiceCheckEbsBiometricStatusNotSupportedExceptionFaultFaultMessage(String message, org.datacontract.schemas._2004._07.system.NotSupportedException notSupportedException, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = notSupportedException;
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-01-18T16:49:03.360+03:00")
    public org.datacontract.schemas._2004._07.system.NotSupportedException getFaultInfo() {
        return this.faultInfo;
    }
}
