package com.rusguard.client;

import jakarta.annotation.Generated;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.1.4
 * 2026-01-18T16:49:04.546+03:00
 * Generated source version: 4.1.4
 *
 */
@WebService(targetNamespace = "http://www.rusguardsecurity.ru", name = "ILSubnetworkSubscribeService")
@XmlSeeAlso({org.datacontract.schemas._2004._07.system_net.ObjectFactory.class, ObjectFactory.class, org.datacontract.schemas._2004._07.vviinvestment_rusguard_dal_entities_entity_workplace.ObjectFactory.class, org.datacontract.schemas._2004._07.system.ObjectFactory.class, org.datacontract.schemas._2004._07.vviinvestment_rusguard_dal_entities_entity.ObjectFactory.class, org.datacontract.schemas._2004._07.vviinvestment_rusguard_dal_entities_entity_screenlayout_cellcontent.ObjectFactory.class, org.datacontract.schemas._2004._07.vviinvestment_rusguard_dal_entities_entity_report.ObjectFactory.class, org.datacontract.schemas._2004._07.vviinvestment_rusguard_dal_entities_driver.ObjectFactory.class, org.datacontract.schemas._2004._07.vviinvestment_rusguard_dal_entities_entity_acs_accesslevels.ObjectFactory.class, com.microsoft.schemas._2003._10.serialization.ObjectFactory.class, org.tempuri.ObjectFactory.class, org.datacontract.schemas._2004._07.rusguard.ObjectFactory.class, generated.ObjectFactory.class, com.microsoft.schemas._2003._10.serialization.arrays.ObjectFactory.class, org.datacontract.schemas._2004._07.system_runtime.ObjectFactory.class, org.datacontract.schemas._2004._07.vviinvestment_rusguard_dal_entities_entity_acs.ObjectFactory.class, org.datacontract.schemas._2004._07.vviinvestment_rusguard_dal_entities.ObjectFactory.class, org.datacontract.schemas._2004._07.vviinvestment_rusguard_net_services.ObjectFactory.class})
@Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-01-18T16:49:04.546+03:00", comments = "Apache CXF 4.1.4")
public interface ILSubnetworkSubscribeService {

    @WebMethod(operationName = "ProcessSubnetworkStateChanged", action = "http://www.rusguardsecurity.ru/ILSubnetworkSubscribeService/ProcessSubnetworkStateChanged")
    @Action(input = "http://www.rusguardsecurity.ru/ILSubnetworkSubscribeService/ProcessSubnetworkStateChanged", output = "http://www.rusguardsecurity.ru/ILSubnetworkSubscribeService/ProcessSubnetworkStateChangedResponse")
    @RequestWrapper(localName = "ProcessSubnetworkStateChanged", targetNamespace = "http://www.rusguardsecurity.ru", className = "com.rusguard.client.ProcessSubnetworkStateChanged")
    @ResponseWrapper(localName = "ProcessSubnetworkStateChangedResponse", targetNamespace = "http://www.rusguardsecurity.ru", className = "com.rusguard.client.ProcessSubnetworkStateChangedResponse")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-01-18T16:49:04.546+03:00")
    public void processSubnetworkStateChanged(

        @WebParam(name = "subnetworkId", targetNamespace = "http://www.rusguardsecurity.ru")
        java.lang.String subnetworkId
    );
}
